In [1]:
import numpy as np
import pandas as pd

In [2]:
path = "/content/drive/MyDrive/mulcam_bigdata/3조 : 최종 프로젝트/김선규/data/추가데이터.csv"

In [3]:
pd.read_csv(path)

,Unnamed: 0,파일이름,질병_카테고리,질병,부서,의도,단어수,폴더명,답변
0,0,HC-A-01995967,순환기질환,고혈압,내과,검진,162,고혈압 - 검진,고혈압 환자의 기본 검진은 최초의 진단과 동시에 시작되어야 합니다. 만약 고혈압이 ...
1,1,HC-A-01995979,순환기질환,고혈압,내과,검진,92,고혈압 - 검진,고혈압의 검진은 정확한 검사와 주기적인 모니터링이 필요한 치료 과정입니다. 고혈압으...
2,2,HC-A-01995982,순환기질환,고혈압,내과,검진,90,고혈압 - 검진,"고혈압이 확인되면, 의사는 환자에게 정기적으로 혈압을 측정하고 결과를 확인하는 것이..."
3,3,HC-A-01995985,순환기질환,고혈압,내과,검진,129,고혈압 - 검진,고혈압의 검진은 정확한 혈압 측정과 다양한 검사를 통해 이루어집니다. 고혈압은 수축...
4,4,HC-A-01995999,순환기질환,고혈압,내과,검진,88,고혈압 - 검진,고혈압을 검진하기 위해서는 여러 가지 방법을 고려할 수 있습니다. 고혈압을 진단받은...
...,...,...,...,...,...,...,...,...,...
50056,7561,HC-A-07104297,근골격질환,좌골신경통,외과,치료,108,좌골신경통 - 치료,"좌골신경통은 치료 가능한 질환이며, 치료 방법은 환자 개개인의 상태와 증상에 따라 ..."
50057,7562,HC-A-07104493,근골격질환,좌골신경통,외과,치료,87,좌골신경통 - 치료,"증상은 좌골신경통의 가장 일반적인 증상 중 하나입니다. 다양한 치료법이 존재하며, ..."
50058,7563,HC-A-07109137,근골격질환,좌골신경통,외과,치료,99,좌골신경통 - 치료,좌골신경통은 일반적으로 통증의 강도와 유발 요인을 최소화하기 위한 다양한 치료 방법...
50059,7564,HC-A-07111605,근골격질환,좌골신경통,외과,치료,72,좌골신경통 - 치료,"좌골신경통의 치료 방법은 다양합니다. 좌골신경통의 치료에는 약물 치료, 물리치료, ..."
50060,7565,HC-A-07113988,근골격질환,좌골신경통,외과,치료,90,좌골신경통 - 치료,"좌골신경통은 치료가 어렵지만 치료 방법은 다양합니다. 보존적 치료, 약물 치료, 수..."

In [6]:
df = pd.read_csv(path, index_col=0)
df.head(3)

,파일이름,질병_카테고리,질병,부서,의도,단어수,폴더명,답변
0,HC-A-01995967,순환기질환,고혈압,내과,검진,162,고혈압 - 검진,고혈압 환자의 기본 검진은 최초의 진단과 동시에 시작되어야 합니다. 만약 고혈압이 ...
1,HC-A-01995979,순환기질환,고혈압,내과,검진,92,고혈압 - 검진,고혈압의 검진은 정확한 검사와 주기적인 모니터링이 필요한 치료 과정입니다. 고혈압으...
2,HC-A-01995982,순환기질환,고혈압,내과,검진,90,고혈압 - 검진,"고혈압이 확인되면, 의사는 환자에게 정기적으로 혈압을 측정하고 결과를 확인하는 것이..."

In [7]:
df.의도.unique()

array(['검진', '식이, 생활', '약물', '예방', '운동', '원인', '정의', '증상', '진단', '치료',
       '재활'], dtype=object)

어떤 의도를 사용할가 = 어떤 서비스를 제공할가