In [8]:
import pandas as pd

In [9]:
path="/content/drive/MyDrive/mulcam_bigdata/3조 : 최종 프로젝트/남학균/data/관절염_답변_재분류_v5.csv"

In [10]:
pd.read_csv(path)

,순서,Main_Category,답변_body,의도,질병_카테고리,질병,부서
0,1,검진,"또한 환자의 관절 기능을 평가하기 위해 증상을 문진하고, X-ray, MRI, 초음...",검진,근골격질환,관절염,재활의학과
1,1,기타,1,검진,근골격질환,관절염,재활의학과
2,1,운동,"증상 평가: 관절염의 초기 증상을 평가하기 위해 의사는 관절 통증, 부종, 운동 제...",검진,근골격질환,관절염,재활의학과
3,2,검진,"신체 검사: 의사는 관절의 부종, 이상 소리, 움직임 제한 등의 증상을 확인하기 위...",검진,근골격질환,관절염,재활의학과
4,2,기타,1. 2. 3. 4. 5. 6. 7. 8.,검진,근골격질환,관절염,재활의학과
...,...,...,...,...,...,...,...
8826,3546,운동,이 외에도 DNA 주사는 콜라겐 생성을 유도하여 관절을 보호하고 관절의 운동 범위를...,치료,근골격질환,관절염,정형외과
8827,3547,기타,연골 주사는 히알루론산과 같은 세포 재생 물질을 사용하여 연골의 흡수 및 재생을 억...,치료,근골격질환,관절염,정형외과
8828,3547,약물,"연골 주사는 관절액에 주입되는 주사약으로, 히알루론산으로 만들어진 관절액으로 관절 ...",치료,근골격질환,관절염,정형외과
8829,3548,기타,이 주사를 반복하여 맞으면 연골이 재생되어 관절의 기능이 개선됩니다.,치료,근골격질환,관절염,정형외과
8830,3548,약물,약물 치료 중에서도 연골 주사가 효과적입니다. 연골 주사는 히알루론산이 주성분인 약...,치료,근골격질환,관절염,정형외과

In [13]:
raw = pd.read_csv(path)
df = raw[raw["의도"]=="진단"]
df.head()

,순서,Main_Category,답변_body,의도,질병_카테고리,질병,부서
3032,1161,검진,관절염의 진단을 위해 의사는 일반적으로 신체검사와 신체검사 소견을 바탕으로 진단을 ...,진단,근골격질환,관절염,류마티스내과
3033,1161,기타,의사는 환자의 손을 사용하여 관절의 상태를 확인하고 이상을 식별합니다.,진단,근골격질환,관절염,류마티스내과
3034,1162,검진,관절염 진단을 위해 다양한 검사법을 사용합니다. 관절 주위 통증이 있는지 여부와 관...,진단,근골격질환,관절염,류마티스내과
3035,1162,증상,환자의 증상과 병력을 조사하는 것은 관절염 진단의 출발점입니다.,진단,근골격질환,관절염,류마티스내과
3036,1163,검진,진단을 위해 의사는 환자의 증상과 검사 결과를 종합적으로 고려합니다.,진단,근골격질환,관절염,류마티스내과

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 410 entries, 3032 to 3441
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   순서             410 non-null    int64
 1   Main_Category  410 non-null    object
 2   답변_body        410 non-null    object
 3   의도             410 non-null    object
 4   질병_카테고리        410 non-null    object
 5   질병             410 non-null    object
 6   부서             410 non-null    object
dtypes: int64(1), object(6)
memory usage: 25.6+ KB

In [15]:
df

,순서,Main_Category,답변_body,의도,질병_카테고리,질병,부서
3032,1161,검진,관절염의 진단을 위해 의사는 일반적으로 신체검사와 신체검사 소견을 바탕으로 진단을 ...,진단,근골격질환,관절염,류마티스내과
3033,1161,기타,의사는 환자의 손을 사용하여 관절의 상태를 확인하고 이상을 식별합니다.,진단,근골격질환,관절염,류마티스내과
3034,1162,검진,관절염 진단을 위해 다양한 검사법을 사용합니다. 관절 주위 통증이 있는지 여부와 관...,진단,근골격질환,관절염,류마티스내과
3035,1162,증상,환자의 증상과 병력을 조사하는 것은 관절염 진단의 출발점입니다.,진단,근골격질환,관절염,류마티스내과
3036,1163,검진,진단을 위해 의사는 환자의 증상과 검사 결과를 종합적으로 고려합니다.,진단,근골격질환,관절염,류마티스내과
...,...,...,...,...,...,...,...
3437,1318,진단,"추가적으로, 환자의 의료 병력, 가족력, 이전 병력, 환경적 요인 등도 진단에 도움...",진단,근골격질환,관절염,류마티스내과
3438,1319,검진,"혈액 검사, 방사선 검사, 그리고 관절 유압을 통해 진단을 수행합니다.",진단,근골격질환,관절염,류마티스내과
3439,1319,원인,"관절염은 관절 주위통이 배제되고 관절통이 확실하며, 관절통이 다른 병리적인 원인에 ...",진단,근골격질환,관절염,류마티스내과
3440,1319,진단,관절통이 관절염에서만 확인되거나 감별 진단이 필요한 경우도 있습니다.,진단,근골격질환,관절염,류마티스내과
3441,1320,검진,관절염의 진단 방법에는 혈액검사와 방사선 검사가 있습니다. 혈액검사에서는 염증 표지...,진단,근골격질환,관절염,류마티스내과

In [16]:
df.to_excel("관절염_진단.xlsx")