In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
path = '/content/drive/MyDrive/mulcam_bigdata/3조 : 최종 프로젝트/김건우/data/문화 빅데이터 플렛폼/KC_ODSN_CNTEDU_FCLTY_LIST_2023.csv'

In [3]:
pd.read_csv(path)

,ESNTL_ID,LCLAS_NM,MLSFC_NM,FCLTY_NM,CTPRVN_CD,CTPRVN_NM,SIGNGU_CD,SIGNGU_NM,LEGALDONG_CD,LEGALDONG_NM,...,BULD_MANAGE_CD,TEL_NO,ZIP_NO,HMPG_URL,FCLTY_LA,FCLTY_LO,ORIGIN_NM,ADIT_DC,UPDT_DT,REGIST_DT
0,KCOEFPO23N000000001,문화시설,문화시설_교육_시니어,전남대학교용봉동캠퍼스평생교육원,29,광주광역시,29170,북구,2917010700,NaN,...,2917010700103000000024363,NaN,61186.0,NaN,35.179328,126.907701,공공데이터,-,20231231,20231231
1,KCOEFPO23N000000002,문화시설,문화시설_교육_시니어,고려대학교평생교육원,11,서울특별시,11290,성북구,1129013500,NaN,...,1129012500100010002039525,NaN,2841.0,NaN,37.590228,127.035858,공공데이터,-,20231231,20231231
2,KCOEFPO23N000000003,문화시설,문화시설_교육_시니어,서울여자대학교평생교육원,11,서울특별시,11350,노원구,1135010300,NaN,...,1135010300101260000014437,NaN,1797.0,NaN,37.627234,127.090297,공공데이터,-,20231231,20231231
3,KCOEFPO23N000000004,문화시설,문화시설_교육_시니어,광주가톨릭평생교육원본관,29,광주광역시,29140,서구,2914011800,NaN,...,2914011800109970001008995,NaN,61995.0,NaN,35.150379,126.868303,공공데이터,-,20231231,20231231
4,KCOEFPO23N000000005,문화시설,문화시설_교육_시니어,세종대학교평생교육원,11,서울특별시,11215,광진구,1121510900,NaN,...,1121510900100980000018572,NaN,5006.0,NaN,37.553244,127.073381,공공데이터,-,20231231,20231231
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
862,KCOEFPO23N000000863,문화시설,문화시설_교육_시니어,충남평생교육원버스정류장,44,부산광역시,44131,해운대구,4413125033,서흥리,...,2635010300202790009007896,NaN,48045.0,NaN,36.770683,127.205620,NaN,NaN,20231231,20231231
863,KCOEFPO23N000000864,문화시설,문화시설_교육_시니어,전북과학대평생교육원버스정류장,45,부산광역시,45180,해운대구,4518010300,서흥리,...,2635010300202790009007896,NaN,48045.0,NaN,35.563621,126.865936,NaN,NaN,20231231,20231231
864,KCOEFPO23N000000865,문화시설,문화시설_교육_시니어,가톨릭대평생교육원버스정류장,29,부산광역시,29140,해운대구,2914011800,서흥리,...,2635010300202790009007896,NaN,48045.0,NaN,35.149342,126.870918,NaN,NaN,20231231,20231231
865,KCOEFPO23N000000866,문화시설,문화시설_교육_시니어,엠지필라테스평생교육원,11,부산광역시,11710,해운대구,1171010400,서흥리,...,2635010300202790009007896,NaN,48045.0,NaN,37.508303,127.107004,NaN,NaN,20231231,20231231
866,KCOEFPO23N000000867,문화시설,문화시설_교육_시니어,부산칼리지평생교육원,26,부산광역시,26350,해운대구,2635010300,서흥리,...,2635010300202790009007896,NaN,48045.0,NaN,35.204625,129.116488,NaN,NaN,20231231,20231231

In [5]:
raw = pd.read_csv(path)
df = raw.copy()
df.head(3)

,ESNTL_ID,LCLAS_NM,MLSFC_NM,FCLTY_NM,CTPRVN_CD,CTPRVN_NM,SIGNGU_CD,SIGNGU_NM,LEGALDONG_CD,LEGALDONG_NM,...,BULD_MANAGE_CD,TEL_NO,ZIP_NO,HMPG_URL,FCLTY_LA,FCLTY_LO,ORIGIN_NM,ADIT_DC,UPDT_DT,REGIST_DT
0,KCOEFPO23N000000001,문화시설,문화시설_교육_시니어,전남대학교용봉동캠퍼스평생교육원,29,광주광역시,29170,북구,2917010700,NaN,...,2917010700103000000024363,NaN,61186.0,NaN,35.179328,126.907701,공공데이터,-,20231231,20231231
1,KCOEFPO23N000000002,문화시설,문화시설_교육_시니어,고려대학교평생교육원,11,서울특별시,11290,성북구,1129013500,NaN,...,1129012500100010002039525,NaN,2841.0,NaN,37.590228,127.035858,공공데이터,-,20231231,20231231
2,KCOEFPO23N000000003,문화시설,문화시설_교육_시니어,서울여자대학교평생교육원,11,서울특별시,11350,노원구,1135010300,NaN,...,1135010300101260000014437,NaN,1797.0,NaN,37.627234,127.090297,공공데이터,-,20231231,20231231

In [10]:
df.columns

Index(['ESNTL_ID', 'LCLAS_NM', 'MLSFC_NM', 'FCLTY_NM', 'CTPRVN_CD',
       'CTPRVN_NM', 'SIGNGU_CD', 'SIGNGU_NM', 'LEGALDONG_CD', 'LEGALDONG_NM',
       'ROAD_NM_CD', 'FCLTY_ROAD_NM_ADDR', 'LNM_ADDR', 'ADDR_ENG_NM',
       'ADSTRD_CD', 'BULD_NM', 'BULD_MANAGE_CD', 'TEL_NO', 'ZIP_NO',
       'HMPG_URL', 'FCLTY_LA', 'FCLTY_LO', 'ORIGIN_NM', 'ADIT_DC', 'UPDT_DT',
       'REGIST_DT'],
      dtype='object')

ESNTL_ID : 고유ID<br>
LCLAS_NM : 대분류명<br>
MLSFC_NM : 중분류명<br>
FCLTY_NM : 시설명<br>
CTPRVN_CD : 시도코드<br>
CTPRVN_NM : 시도명<br>
SIGNGU_CD : 시군구코드<br>
SIGNGU_NM : 시군구명<br>
LEGALDONG_CD : 법정동코드<br>
LEGALDONG_NM : 법정동명<br>
ROAD_NM_CD : 도로명코드<br>
FCLTY_ROAD_NM_ADDR : 시설도로명주소<br>
LNM_ADDR : 지번주소<br>
ADDR_ENG_NM : 주소영문명<br>
ADSTRD_CD : 행정동코드<br>
BULD_NM : 건물명<br>
BULD_MANAGE_CD : 건물관리코드<br>
TEL_NO : 전화번호<br>
ZIP_NO : 우편번호<br>
HMPG_URL : 홈페이지URL<br>
FCLTY_LA : 시설위도<br>
FCLTY_LO : 시설경도<br>
ORIGIN_NM : 출처명<br>
ADIT_DC : 추가설명<br>
UPDT_DT : 수정일시<br>
REGIST_DT : 등록일시<br>

In [6]:
df.shape

(867, 26)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 867 entries, 0 to 866
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ESNTL_ID            867 non-null    object
 1   LCLAS_NM            867 non-null    object
 2   MLSFC_NM            867 non-null    object
 3   FCLTY_NM            867 non-null    object
 4   CTPRVN_CD           867 non-null    int64
 5   CTPRVN_NM           857 non-null    object
 6   SIGNGU_CD           867 non-null    int64
 7   SIGNGU_NM           857 non-null    object
 8   LEGALDONG_CD        867 non-null    int64
 9   LEGALDONG_NM        108 non-null    object
 10  ROAD_NM_CD          857 non-null    float64
 11  FCLTY_ROAD_NM_ADDR  858 non-null    object
 12  LNM_ADDR            865 non-null    object
 13  ADDR_ENG_NM         857 non-null    object
 14  ADSTRD_CD           857 non-null    float64
 15  BULD_NM             504 non-null    object
 16  BULD_MANAGE_CD      857 non-null    object
 17  TEL_NO              9 non-null      float64
 18  ZIP_NO              857 non-null    float64
 19  HMPG_URL            0 non-null      float64
 20  FCLTY_LA            867 non-null    float64
 21  FCLTY_LO            867 non-null    float64
 22  ORIGIN_NM           853 non-null    object
 23  ADIT_DC             853 non-null    object
 24  UPDT_DT             867 non-null    int64
 25  REGIST_DT           867 non-null    int64
dtypes: float64(7), int64(5), object(14)
memory usage: 176.2+ KB

In [8]:
df.isnull().sum()

ESNTL_ID                0
LCLAS_NM                0
MLSFC_NM                0
FCLTY_NM                0
CTPRVN_CD               0
CTPRVN_NM              10
SIGNGU_CD               0
SIGNGU_NM              10
LEGALDONG_CD            0
LEGALDONG_NM          759
ROAD_NM_CD             10
FCLTY_ROAD_NM_ADDR      9
LNM_ADDR                2
ADDR_ENG_NM            10
ADSTRD_CD              10
BULD_NM               363
BULD_MANAGE_CD         10
TEL_NO                858
ZIP_NO                 10
HMPG_URL              867
FCLTY_LA                0
FCLTY_LO                0
ORIGIN_NM              14
ADIT_DC                14
UPDT_DT                 0
REGIST_DT               0
dtype: int64

In [9]:
df.describe()

,CTPRVN_CD,SIGNGU_CD,LEGALDONG_CD,ROAD_NM_CD,ADSTRD_CD,TEL_NO,ZIP_NO,HMPG_URL,FCLTY_LA,FCLTY_LO,UPDT_DT,REGIST_DT
count,867.000000,867.000000,8.670000e+02,8.570000e+02,8.570000e+02,9.000000e+00,857.000000,0.0,867.000000,867.000000,867.0,867.0
mean,32.010381,32304.973472,3.230511e+09,3.242115e+11,3.242094e+09,9.485957e+08,29732.768961,NaN,36.540793,127.499681,20231231.0,20231231.0
std,13.538795,13472.254594,1.347228e+09,1.381466e+11,1.381467e+09,2.312431e+09,19449.588778,NaN,1.014984,0.822104,0.0,0.0
min,11.000000,11110.000000,1.111011e+09,1.111021e+11,1.111011e+09,0.000000e+00,1069.000000,NaN,33.344149,126.322725,20231231.0,20231231.0
25%,26.000000,26230.000000,2.623011e+09,2.623042e+11,2.623011e+09,1.644553e+07,10518.000000,NaN,35.780095,126.918529,20231231.0,20231231.0
50%,31.000000,31110.000000,3.111012e+09,3.020043e+11,3.020013e+09,2.866136e+07,31233.000000,NaN,36.771743,127.093440,20231231.0,20231231.0
75%,44.000000,44150.000000,4.415011e+09,4.413333e+11,4.413310e+09,5.180366e+08,47209.000000,NaN,37.498519,128.157627,20231231.0,20231231.0
max,51.000000,51810.000000,5.181033e+09,5.275033e+11,5.275034e+09,7.086542e+09,63632.000000,NaN,38.209590,129.416235,20231231.0,20231231.0