In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
path = '/content/drive/MyDrive/mulcam_bigdata/3조 : 최종 프로젝트/김건우/data/문화 빅데이터 플렛폼/KC_ODSN_CLTUR_FCLTY_LIST_2023.csv'

In [3]:
pd.read_csv(path)

,ESNTL_ID,LCLAS_NM,MLSFC_NM,FCLTY_NM,CTPRVN_CD,CTPRVN_NM,SIGNGU_CD,SIGNGU_NM,LEGALDONG_CD,LEGALDONG_NM,...,BULD_MANAGE_CD,TEL_NO,ZIP_NO,HMPG_URL,FCLTY_LA,FCLTY_LO,ORIGIN_NM,ADIT_DC,UPDT_DT,REGIST_DT
0,KCOCFPO23N000000001,시니어,문화시설,송죽,27.0,대구광역시,27200.0,남구,2.720010e+09,이천동,...,2720010100104340000000000,534758756.0,42423.0,-,128.597311,35.853333,공공데이터,할인적용최소연령 : 65,20231231,20231231
1,KCOCFPO23N000000002,시니어,문화시설,엘르리여쌤뷰티,27.0,대구광역시,27200.0,남구,2.720010e+09,이천동,...,2720010100102790000000000,534752363.0,42433.0,-,128.605475,35.852442,공공데이터,할인적용최소연령 : 65,20231231,20231231
2,KCOCFPO23N000000003,시니어,문화시설,신화,27.0,대구광역시,27200.0,남구,2.720010e+09,봉덕동,...,2720010200105080000000000,534745567.0,42428.0,-,128.596576,35.849782,공공데이터,할인적용최소연령 : 65,20231231,20231231
3,KCOCFPO23N000000004,시니어,문화시설,백합,27.0,대구광역시,27200.0,남구,2.720010e+09,봉덕동,...,2720010200107460000000000,534754048.0,42438.0,-,128.599830,35.846787,공공데이터,할인적용최소연령 : 65,20231231,20231231
4,KCOCFPO23N000000005,시니어,문화시설,선경 미용실,27.0,대구광역시,27200.0,남구,2.720010e+09,봉덕동,...,2720010200105460000000000,536265584.0,42428.0,-,128.595753,35.847762,공공데이터,할인적용최소연령 : 65,20231231,20231231
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2096,KCOCFPO23N000000257,시니어,문화시설,여유당전통찻집,52.0,전북특별자치도,52180.0,정읍시,4.518010e+09,수성동,...,4518010100106440000000000,NaN,56165.0,-,35.567031,126.856521,공공데이터,-,20231231,20231231
2097,KCOCFPO23N000000258,시니어,문화시설,청림원전통찻집,41.0,경기도,41550.0,안성시,4.155012e+09,사곡동,...,4155012300100300000000000,NaN,17539.0,-,37.035745,127.267154,공공데이터,-,20231231,20231231
2098,KCOCFPO23N000000259,시니어,문화시설,전통찻집,46.0,전라남도,46110.0,목포시,4.611016e+09,옥암동,...,4611016400110910000000000,NaN,58746.0,-,34.800839,126.434966,공공데이터,-,20231231,20231231
2099,KCOCFPO23N000000260,시니어,문화시설,향인전통찻집,52.0,전북특별자치도,52111.0,전주시 완산구,4.511114e+09,중인동,...,4511113500108670000000000,NaN,55144.0,-,35.765267,127.093126,공공데이터,-,20231231,20231231
2100,KCOCFPO23N000000261,시니어,문화시설,대현동전통찻집,11.0,서울특별시,11410.0,서대문구,1.141011e+09,대현동,...,1141011200100270000000000,NaN,3766.0,-,37.558066,126.943174,공공데이터,-,20231231,20231231

In [10]:
df.columns

Index(['ESNTL_ID', 'LCLAS_NM', 'MLSFC_NM', 'FCLTY_NM', 'CTPRVN_CD',
       'CTPRVN_NM', 'SIGNGU_CD', 'SIGNGU_NM', 'LEGALDONG_CD', 'LEGALDONG_NM',
       'ROAD_NM_CD', 'FCLTY_ROAD_NM_ADDR', 'LNM_ADDR', 'ADDR_ENG_NM',
       'ADSTRD_CD', 'BULD_NM', 'BULD_MANAGE_CD', 'TEL_NO', 'ZIP_NO',
       'HMPG_URL', 'FCLTY_LA', 'FCLTY_LO', 'ORIGIN_NM', 'ADIT_DC', 'UPDT_DT',
       'REGIST_DT'],
      dtype='object')

ESNTL_ID : 고유ID<br>
LCLAS_NM : 대분류명<br>
MLSFC_NM : 중분류명<br>
FCLTY_NM : 시설명<br>
CTPRVN_CD : 시도코드<br>
CTPRVN_NM : 시도명<br>
SIGNGU_CD : 시군구코드<br>
SIGNGU_NM : 시군구명<br>
LEGALDONG_CD : 법정동코드<br>
LEGALDONG_NM : 법정동명<br>
ROAD_NM_CD : 도로명코드<br>
FCLTY_ROAD_NM_ADDR : 시설도로명주소<br>
LNM_ADDR : 지번주소<br>
ADDR_ENG_NM : 주소영문명<br>
ADSTRD_CD : 행정동코드<br>
BULD_NM : 건물명<br>
BULD_MANAGE_CD : 건물관리코드<br>
TEL_NO : 전화번호<br>
ZIP_NO : 우편번호<br>
HMPG_URL : 홈페이지URL<br>
FCLTY_LA : 시설위도<br>
FCLTY_LO : 시설경도<br>
ORIGIN_NM : 출처명<br>
ADIT_DC : 추가설명<br>
UPDT_DT : 수정일시<br>
REGIST_DT : 등록일시<br>

In [5]:
raw = pd.read_csv(path)
df = raw.copy()
df.head(3)

,ESNTL_ID,LCLAS_NM,MLSFC_NM,FCLTY_NM,CTPRVN_CD,CTPRVN_NM,SIGNGU_CD,SIGNGU_NM,LEGALDONG_CD,LEGALDONG_NM,...,BULD_MANAGE_CD,TEL_NO,ZIP_NO,HMPG_URL,FCLTY_LA,FCLTY_LO,ORIGIN_NM,ADIT_DC,UPDT_DT,REGIST_DT
0,KCOCFPO23N000000001,시니어,문화시설,송죽,27.0,대구광역시,27200.0,남구,2.720010e+09,이천동,...,2720010100104340000000000,534758756.0,42423.0,-,128.597311,35.853333,공공데이터,할인적용최소연령 : 65,20231231,20231231
1,KCOCFPO23N000000002,시니어,문화시설,엘르리여쌤뷰티,27.0,대구광역시,27200.0,남구,2.720010e+09,이천동,...,2720010100102790000000000,534752363.0,42433.0,-,128.605475,35.852442,공공데이터,할인적용최소연령 : 65,20231231,20231231
2,KCOCFPO23N000000003,시니어,문화시설,신화,27.0,대구광역시,27200.0,남구,2.720010e+09,봉덕동,...,2720010200105080000000000,534745567.0,42428.0,-,128.596576,35.849782,공공데이터,할인적용최소연령 : 65,20231231,20231231

In [6]:
df.shape

(2101, 26)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2101 entries, 0 to 2100
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ESNTL_ID            2101 non-null   object
 1   LCLAS_NM            2101 non-null   object
 2   MLSFC_NM            2101 non-null   object
 3   FCLTY_NM            2101 non-null   object
 4   CTPRVN_CD           1982 non-null   float64
 5   CTPRVN_NM           2101 non-null   object
 6   SIGNGU_CD           1982 non-null   float64
 7   SIGNGU_NM           2100 non-null   object
 8   LEGALDONG_CD        1944 non-null   float64
 9   LEGALDONG_NM        1944 non-null   object
 10  ROAD_NM_CD          1982 non-null   float64
 11  FCLTY_ROAD_NM_ADDR  2097 non-null   object
 12  LNM_ADDR            2095 non-null   object
 13  ADDR_ENG_NM         1982 non-null   object
 14  ADSTRD_CD           1982 non-null   float64
 15  BULD_NM             488 non-null    object
 16  BULD_MANAGE_CD      1982 non-null   object
 17  TEL_NO              1840 non-null   float64
 18  ZIP_NO              2081 non-null   float64
 19  HMPG_URL            1944 non-null   object
 20  FCLTY_LA            2101 non-null   float64
 21  FCLTY_LO            2101 non-null   float64
 22  ORIGIN_NM           2101 non-null   object
 23  ADIT_DC             2101 non-null   object
 24  UPDT_DT             2101 non-null   int64
 25  REGIST_DT           2101 non-null   int64
dtypes: float64(9), int64(2), object(15)
memory usage: 426.9+ KB

In [8]:
df.isnull().sum()

ESNTL_ID                 0
LCLAS_NM                 0
MLSFC_NM                 0
FCLTY_NM                 0
CTPRVN_CD              119
CTPRVN_NM                0
SIGNGU_CD              119
SIGNGU_NM                1
LEGALDONG_CD           157
LEGALDONG_NM           157
ROAD_NM_CD             119
FCLTY_ROAD_NM_ADDR       4
LNM_ADDR                 6
ADDR_ENG_NM            119
ADSTRD_CD              119
BULD_NM               1613
BULD_MANAGE_CD         119
TEL_NO                 261
ZIP_NO                  20
HMPG_URL               157
FCLTY_LA                 0
FCLTY_LO                 0
ORIGIN_NM                0
ADIT_DC                  0
UPDT_DT                  0
REGIST_DT                0
dtype: int64

In [9]:
df.describe()

,CTPRVN_CD,SIGNGU_CD,LEGALDONG_CD,ROAD_NM_CD,ADSTRD_CD,TEL_NO,ZIP_NO,FCLTY_LA,FCLTY_LO,UPDT_DT,REGIST_DT
count,1982.000000,1982.000000,1.944000e+03,1.982000e+03,1.982000e+03,1.840000e+03,2081.000000,2101.000000,2101.000000,2101.0,2101.0
mean,28.703330,28990.191221,2.843097e+09,2.899057e+11,2.899032e+09,3.927086e+08,26990.308025,116.311469,48.042936,20231231.0,20231231.0
std,13.329164,13286.340910,1.286165e+09,1.328635e+11,1.328636e+09,6.679634e+08,16838.600711,30.185145,29.949010,0.0,0.0
min,11.000000,11110.000000,1.111012e+09,1.111031e+11,1.111012e+09,0.000000e+00,1025.000000,33.507643,35.168912,20231231.0,20231231.0
25%,11.000000,11560.000000,1.156013e+09,1.156042e+11,1.156013e+09,2.221365e+08,7400.000000,126.897818,35.870458,20231231.0,20231231.0
50%,28.000000,28177.000000,2.817710e+09,2.817743e+11,2.817710e+09,3.246940e+08,24854.000000,127.074676,37.441537,20231231.0,20231231.0
75%,41.000000,41113.000000,4.111514e+09,4.111343e+11,4.111314e+09,5.300000e+08,42492.000000,128.553023,37.539201,20231231.0,20231231.0
max,52.000000,52800.000000,5.183031e+09,5.280046e+11,5.280041e+09,7.088201e+09,63334.000000,129.457852,129.416484,20231231.0,20231231.0