In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
path = '/content/drive/MyDrive/mulcam_bigdata/3조 : 최종 프로젝트/김건우/data/문화 빅데이터 플렛폼/KC_ODSN_WALK_RECOMEND_LIST_2023.csv'

In [3]:
pd.read_csv(path)

,ESNTL_ID,LCLAS_NM,MLSFC_NM,FCLTY_NM,CTPRVN_CD,CTPRVN_NM,SIGNGU_CD,SIGNGU_NM,LEGALDONG_CD,LEGALDONG_NM,...,BULD_MANAGE_CD,TEL_NO,ZIP_NO,HMPG_URL,FCLTY_LA,FCLTY_LO,ORIGIN_NM,ADIT_DC,UPDT_DT,REGIST_DT
0,KCOWRPO23N000000001,쇼핑시설,쇼핑시설_전통시장,원미부흥시장,41,경기도,41190,부천시 원미구,4119010100,원미동,...,4119510100101180000000000,0.0,14571.0,0.0,37.553516,126.921715,공공데이터,상설장,20231231,20231231
1,KCOWRPO23N000000002,쇼핑시설,쇼핑시설_전통시장,원미종합시장,41,경기도,41190,부천시 원미구,4119010100,원미동,...,4119510100100970000000000,0.0,14568.0,0.0,37.545392,126.953319,공공데이터,상설장,20231231,20231231
2,KCOWRPO23N000000003,자연,자연_공원,원미별빛,41,경기도,41190,부천시 원미구,4119010100,원미동,...,4119510100101270000000000,0.0,14571.0,0.0,37.491966,126.787309,공공데이터,-,20231231,20231231
3,KCOWRPO23N000000004,자연,자연_공원,원미,41,경기도,41190,부천시 원미구,4119010100,원미동,...,4119510100100150000000000,0.0,14659.0,0.0,37.497985,126.799040,공공데이터,-,20231231,20231231
4,KCOWRPO23N000000005,쇼핑시설,쇼핑시설_전통시장,음성시장,43,충청북도,43770,음성군,4377025021,읍내리,...,4377025021102490000000000,0.0,27697.0,0.0,36.938166,127.692127,공공데이터,5일장,20231231,20231231
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18682,KCOWRPO23N000018683,자연,자연_공원,강하 소공원,41,경기도,41830,양평군,4183032021,운심리,...,4183032021100280000000000,0.0,12574.0,0.0,37.496164,127.412326,공공데이터,-,20231231,20231231
18683,KCOWRPO23N000018684,자연,자연_공원,한강아트로드 공원,41,경기,41830,양평군,4183032021,강하면 운심리,...,NaN,0.0,NaN,0.0,37.496021,127.408216,공공데이터,-,20231231,20231231
18684,KCOWRPO23N000018685,자연,자연_공원,공흥 소공원,41,경기,41830,양평군,4183025025,양평읍 공흥리,...,NaN,0.0,NaN,0.0,37.493844,127.509326,공공데이터,-,20231231,20231231
18685,KCOWRPO23N000018686,자연,자연_공원,광탄3호 소공원,41,경기,41830,양평군,4183040027,용문면 광탄리,...,NaN,0.0,NaN,0.0,37.508443,127.627414,공공데이터,-,20231231,20231231
18686,KCOWRPO23N000018687,자연,자연_공원,광탄2호 소공원,41,경기,41830,양평군,4183040027,용문면 광탄리,...,NaN,0.0,NaN,0.0,37.509628,127.628406,공공데이터,-,20231231,20231231

In [4]:
raw = pd.read_csv(path)
df = raw.copy()
df.head(3)

,ESNTL_ID,LCLAS_NM,MLSFC_NM,FCLTY_NM,CTPRVN_CD,CTPRVN_NM,SIGNGU_CD,SIGNGU_NM,LEGALDONG_CD,LEGALDONG_NM,...,BULD_MANAGE_CD,TEL_NO,ZIP_NO,HMPG_URL,FCLTY_LA,FCLTY_LO,ORIGIN_NM,ADIT_DC,UPDT_DT,REGIST_DT
0,KCOWRPO23N000000001,쇼핑시설,쇼핑시설_전통시장,원미부흥시장,41,경기도,41190,부천시 원미구,4119010100,원미동,...,4119510100101180000000000,0.0,14571.0,0.0,37.553516,126.921715,공공데이터,상설장,20231231,20231231
1,KCOWRPO23N000000002,쇼핑시설,쇼핑시설_전통시장,원미종합시장,41,경기도,41190,부천시 원미구,4119010100,원미동,...,4119510100100970000000000,0.0,14568.0,0.0,37.545392,126.953319,공공데이터,상설장,20231231,20231231
2,KCOWRPO23N000000003,자연,자연_공원,원미별빛,41,경기도,41190,부천시 원미구,4119010100,원미동,...,4119510100101270000000000,0.0,14571.0,0.0,37.491966,126.787309,공공데이터,-,20231231,20231231

In [5]:
df.columns

Index(['ESNTL_ID', 'LCLAS_NM', 'MLSFC_NM', 'FCLTY_NM', 'CTPRVN_CD',
       'CTPRVN_NM', 'SIGNGU_CD', 'SIGNGU_NM', 'LEGALDONG_CD', 'LEGALDONG_NM',
       'ROAD_NM_CD', 'FCLTY_ROAD_NM_ADDR', 'LNM_ADDR', 'ADDR_ENG_NM',
       'ADSTRD_CD', 'BULD_NM', 'BULD_MANAGE_CD', 'TEL_NO', 'ZIP_NO',
       'HMPG_URL', 'FCLTY_LA', 'FCLTY_LO', 'ORIGIN_NM', 'ADIT_DC', 'UPDT_DT',
       'REGIST_DT'],
      dtype='object')

ESNTL_ID : 고유ID<br>
LCLAS_NM : 대분류명<br>
MLSFC_NM : 중분류명<br>
FCLTY_NM : 시설명<br>
CTPRVN_CD : 시도코드<br>
CTPRVN_NM : 시도명<br>
SIGNGU_CD : 시군구코드<br>
SIGNGU_NM : 시군구명<br>
LEGALDONG_CD : 법정동코드<br>
LEGALDONG_NM : 법정동명<br>
ROAD_NM_CD : 도로명코드<br>
FCLTY_ROAD_NM_ADDR : 시설도로명주소<br>
LNM_ADDR : 지번주소<br>
ADDR_ENG_NM : 주소영문명<br>
ADSTRD_CD : 행정동코드<br>
BULD_NM : 건물명<br>
BULD_MANAGE_CD : 건물관리코드<br>
TEL_NO : 전화번호<br>
ZIP_NO : 우편번호<br>
HMPG_URL : 홈페이지URL<br>
FCLTY_LA : 시설위도<br>
FCLTY_LO : 시설경도<br>
ORIGIN_NM : 출처명<br>
ADIT_DC : 추가설명<br>
UPDT_DT : 수정일시<br>
REGIST_DT : 등록일시<br>

In [6]:
df.shape

(18687, 26)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18687 entries, 0 to 18686
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ESNTL_ID            18687 non-null  object
 1   LCLAS_NM            18687 non-null  object
 2   MLSFC_NM            18687 non-null  object
 3   FCLTY_NM            18687 non-null  object
 4   CTPRVN_CD           18687 non-null  int64
 5   CTPRVN_NM           18687 non-null  object
 6   SIGNGU_CD           18687 non-null  int64
 7   SIGNGU_NM           18625 non-null  object
 8   LEGALDONG_CD        18687 non-null  int64
 9   LEGALDONG_NM        18687 non-null  object
 10  ROAD_NM_CD          18438 non-null  float64
 11  FCLTY_ROAD_NM_ADDR  10253 non-null  object
 12  LNM_ADDR            18687 non-null  object
 13  ADDR_ENG_NM         7401 non-null   object
 14  ADSTRD_CD           8655 non-null   float64
 15  BULD_NM             4890 non-null   object
 16  BULD_MANAGE_CD      7401 non-null   object
 17  TEL_NO              18477 non-null  float64
 18  ZIP_NO              9896 non-null   float64
 19  HMPG_URL            18477 non-null  float64
 20  FCLTY_LA            18687 non-null  float64
 21  FCLTY_LO            18687 non-null  float64
 22  ORIGIN_NM           18687 non-null  object
 23  ADIT_DC             18687 non-null  object
 24  UPDT_DT             18687 non-null  int64
 25  REGIST_DT           18687 non-null  int64
dtypes: float64(7), int64(5), object(14)
memory usage: 3.7+ MB

In [8]:
df.isnull().sum()

ESNTL_ID                  0
LCLAS_NM                  0
MLSFC_NM                  0
FCLTY_NM                  0
CTPRVN_CD                 0
CTPRVN_NM                 0
SIGNGU_CD                 0
SIGNGU_NM                62
LEGALDONG_CD              0
LEGALDONG_NM              0
ROAD_NM_CD              249
FCLTY_ROAD_NM_ADDR     8434
LNM_ADDR                  0
ADDR_ENG_NM           11286
ADSTRD_CD             10032
BULD_NM               13797
BULD_MANAGE_CD        11286
TEL_NO                  210
ZIP_NO                 8791
HMPG_URL                210
FCLTY_LA                  0
FCLTY_LO                  0
ORIGIN_NM                 0
ADIT_DC                   0
UPDT_DT                   0
REGIST_DT                 0
dtype: int64

In [9]:
df.describe()

,CTPRVN_CD,SIGNGU_CD,LEGALDONG_CD,ROAD_NM_CD,ADSTRD_CD,TEL_NO,ZIP_NO,HMPG_URL,FCLTY_LA,FCLTY_LO,UPDT_DT,REGIST_DT
count,18687.000000,18687.000000,1.868700e+04,1.843800e+04,8.655000e+03,1.847700e+04,9896.000000,18477.0,18687.000000,18687.000000,18687.0,18687.0
mean,36.816771,37137.778777,3.701664e+09,1.851901e+11,3.748244e+09,2.355039e+07,30301.115198,0.0,36.436926,127.276358,20231231.0,20231231.0
std,12.016228,12014.902960,1.220372e+09,2.043106e+11,1.258719e+09,2.454766e+08,18251.335021,0.0,1.932678,5.433402,0.0,0.0
min,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1007.000000,0.0,0.000000,0.000000,20231231.0,20231231.0
25%,29.000000,29155.000000,2.914013e+09,0.000000e+00,2.823711e+09,0.000000e+00,14567.000000,0.0,35.799819,126.880981,20231231.0,20231231.0
50%,41.000000,41550.000000,4.150011e+09,1.114041e+11,4.139010e+09,0.000000e+00,28354.500000,0.0,36.719454,127.115347,20231231.0,20231231.0
75%,45.000000,45113.000000,4.511312e+09,4.131044e+11,4.713032e+09,0.000000e+00,46739.000000,0.0,37.435080,128.182649,20231231.0,20231231.0
max,52.000000,52800.000000,5.280041e+09,5.280046e+11,5.280041e+09,7.089614e+09,63643.000000,0.0,38.491555,162.920004,20231231.0,20231231.0