# 1. 샘플링 데이터셋

In [1]:
import numpy as np
import pandas as pd

In [2]:
path = "/content/drive/MyDrive/mulcam_bigdata/3조 : 최종 프로젝트/김성원/Data/헬스케어데이터/샘플링"

In [3]:
sample_q = pd.read_csv(path + "/근골격질환_질문_train.csv")
sample_a = pd.read_csv(path + "/근골격질환_답변_train.csv")

In [4]:
sample_q.head()

,파일이름,참가자_ID,성별,나이,직업,질병여부,지역,질병_카테고리,질병,의도,질문,개체_ID,개체_text,개체_entity,개체_position,단어수,폴더명,유형
0,HC-Q-0485726,QC009,여성,50대 이상,주부,False,부산/대구/울산/경상,근골격질환,VDT 증후군,예방,스마트폰 사용을 줄이면 VDT 증후군 예방에 도움이 될까요?,0.0,VDT 증후군,질환명,13.0,8,VDT 증후군 - 예방,예방
1,HC-Q-0485727,QC010,여성,30대,무직,False,부산/대구/울산/경상,근골격질환,VDT 증후군,예방,"화면 밝기, 글자 크기, 배경색을 조정하여 VDT 증후군을 예방하는 방법을 알려주세요.",0.0,VDT 증후군,질환명,24.0,11,VDT 증후군 - 예방,예방
2,HC-Q-0485728,QC010,여성,30대,무직,False,부산/대구/울산/경상,근골격질환,VDT 증후군,예방,VDT 증후군 예방을 위한 화면 설정 조정 방법에 대해 알려주세요.,0.0,VDT 증후군,질환명,0.0,10,VDT 증후군 - 예방,예방
3,HC-Q-0485729,QC274,여성,40대,주부,False,서울/경기/인천,근골격질환,VDT 증후군,예방,VDT 증후군을 예방하기 위한 방법을 알려주세요.,0.0,VDT 증후군,질환명,0.0,6,VDT 증후군 - 예방,예방
4,HC-Q-0485730,QC147,여성,40대,사무직,False,대전/세종/충청/강원,근골격질환,VDT 증후군,예방,작업 시간 중 모니터를 오랫동안 보는 것이 VDT 증후군 예방에 도움이 되는지 알려...,0.0,VDT 증후군,질환명,24.0,13,VDT 증후군 - 예방,예방

In [5]:
sample_a.head()

,파일이름,질병_카테고리,질병,부서,의도,답변_intro,답변_body,답변_conclusion,단어수,폴더명,유형
0,HC-A-02478483,근골격질환,VDT 증후군,정형외과,예방,VDT 증후군을 예방하기 위한 추가적인 조치를 취할 수 있습니다.,작업 환경의 개선 외에도 건강한 라이프스타일을 유지하는 것이 중요합니다. 작업 자세...,VDT 증후군 예방을 위해서는 건강한 라이프스타일을 유지하고 자세와 자세 조절에 신...,97,VDT 증후군 - 예방,예방
1,HC-A-02478488,근골격질환,VDT 증후군,정형외과,예방,"VDT 증후군은 오랜 시간 동안 컴퓨터를 사용하면서 발생하는 근골격계 장애로, 예방...",바른 자세를 유지하는 것이 VDT 증후군 예방의 첫걸음입니다. 컴퓨터 작업 시 눈과...,"VDT 증후군 예방을 위해 컴퓨터 사용 시 자세의 중요성을 인식하고, 눈과 몸을 일...",93,VDT 증후군 - 예방,예방
2,HC-A-02478491,근골격질환,VDT 증후군,정형외과,예방,VDT(Visual Display Terminal) 증후군을 예방하기 위해 몇 가지...,"첫째로, 올바른 자세와 자세 보정 기술을 유지하는 것이 중요합니다. 눈과 모니터의 ...","VDT 증후군을 예방하기 위해서는 올바른 자세 유지, 화면 밝기 조절, 손목 받침대...",107,VDT 증후군 - 예방,예방
3,HC-A-02478500,근골격질환,VDT 증후군,정형외과,예방,VDT 증후군은 장시간 앉아 컴퓨터 작업을 하는 사람들에게 흔한 문제입니다. 이러한...,"먼저, 올바른 자세를 유지해야 합니다. 키보드와 마우스를 사용할 때 손목이 편안한 ...","이러한 예방 조치를 적용하면 VDT 증후군에 대한 위험을 줄일 수 있으며, 건강한 ...",84,VDT 증후군 - 예방,예방
4,HC-A-02478503,근골격질환,VDT 증후군,정형외과,예방,VDT 증후군의 예방을 위해 올바른 자세와 작업환경이 중요합니다.,"화면을 아래로 향하는 자세는 모니터를 볼 때 등과 허리에 압력을 가할 수 있으며, ...",VDT 증후군의 예방을 위해 올바른 자세와 작업환경을 유지하는 것이 중요합니다.,72,VDT 증후군 - 예방,예방

In [6]:
sample_a['답변'] = sample_a.apply(lambda x: ' '.join([x['답변_intro'], x['답변_body'], x['답변_conclusion']]), axis=1)
sample_a.head()

,파일이름,질병_카테고리,질병,부서,의도,답변_intro,답변_body,답변_conclusion,단어수,폴더명,유형,답변
0,HC-A-02478483,근골격질환,VDT 증후군,정형외과,예방,VDT 증후군을 예방하기 위한 추가적인 조치를 취할 수 있습니다.,작업 환경의 개선 외에도 건강한 라이프스타일을 유지하는 것이 중요합니다. 작업 자세...,VDT 증후군 예방을 위해서는 건강한 라이프스타일을 유지하고 자세와 자세 조절에 신...,97,VDT 증후군 - 예방,예방,VDT 증후군을 예방하기 위한 추가적인 조치를 취할 수 있습니다. 작업 환경의 개선...
1,HC-A-02478488,근골격질환,VDT 증후군,정형외과,예방,"VDT 증후군은 오랜 시간 동안 컴퓨터를 사용하면서 발생하는 근골격계 장애로, 예방...",바른 자세를 유지하는 것이 VDT 증후군 예방의 첫걸음입니다. 컴퓨터 작업 시 눈과...,"VDT 증후군 예방을 위해 컴퓨터 사용 시 자세의 중요성을 인식하고, 눈과 몸을 일...",93,VDT 증후군 - 예방,예방,"VDT 증후군은 오랜 시간 동안 컴퓨터를 사용하면서 발생하는 근골격계 장애로, 예방..."
2,HC-A-02478491,근골격질환,VDT 증후군,정형외과,예방,VDT(Visual Display Terminal) 증후군을 예방하기 위해 몇 가지...,"첫째로, 올바른 자세와 자세 보정 기술을 유지하는 것이 중요합니다. 눈과 모니터의 ...","VDT 증후군을 예방하기 위해서는 올바른 자세 유지, 화면 밝기 조절, 손목 받침대...",107,VDT 증후군 - 예방,예방,VDT(Visual Display Terminal) 증후군을 예방하기 위해 몇 가지...
3,HC-A-02478500,근골격질환,VDT 증후군,정형외과,예방,VDT 증후군은 장시간 앉아 컴퓨터 작업을 하는 사람들에게 흔한 문제입니다. 이러한...,"먼저, 올바른 자세를 유지해야 합니다. 키보드와 마우스를 사용할 때 손목이 편안한 ...","이러한 예방 조치를 적용하면 VDT 증후군에 대한 위험을 줄일 수 있으며, 건강한 ...",84,VDT 증후군 - 예방,예방,VDT 증후군은 장시간 앉아 컴퓨터 작업을 하는 사람들에게 흔한 문제입니다. 이러한...
4,HC-A-02478503,근골격질환,VDT 증후군,정형외과,예방,VDT 증후군의 예방을 위해 올바른 자세와 작업환경이 중요합니다.,"화면을 아래로 향하는 자세는 모니터를 볼 때 등과 허리에 압력을 가할 수 있으며, ...",VDT 증후군의 예방을 위해 올바른 자세와 작업환경을 유지하는 것이 중요합니다.,72,VDT 증후군 - 예방,예방,VDT 증후군의 예방을 위해 올바른 자세와 작업환경이 중요합니다. 화면을 아래로 향...

In [7]:
sample_a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104181 entries, 0 to 104180
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   파일이름           104181 non-null  object
 1   질병_카테고리        104181 non-null  object
 2   질병             104181 non-null  object
 3   부서             104181 non-null  object
 4   의도             104181 non-null  object
 5   답변_intro       104181 non-null  object
 6   답변_body        104181 non-null  object
 7   답변_conclusion  104181 non-null  object
 8   단어수            104181 non-null  int64
 9   폴더명            104181 non-null  object
 10  유형             104181 non-null  object
 11  답변             104181 non-null  object
dtypes: int64(1), object(11)
memory usage: 9.5+ MB

In [8]:
sample_q.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97394 entries, 0 to 97393
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   파일이름         97394 non-null  object
 1   참가자_ID       97394 non-null  object
 2   성별           97394 non-null  object
 3   나이           97394 non-null  object
 4   직업           97394 non-null  object
 5   질병여부         97394 non-null  bool
 6   지역           97394 non-null  object
 7   질병_카테고리      97394 non-null  object
 8   질병           97394 non-null  object
 9   의도           97394 non-null  object
 10  질문           97394 non-null  object
 11  개체_ID        91569 non-null  float64
 12  개체_text      91569 non-null  object
 13  개체_entity    91569 non-null  object
 14  개체_position  91569 non-null  float64
 15  단어수          97394 non-null  int64
 16  폴더명          97394 non-null  object
 17  유형           97394 non-null  object
dtypes: bool(1), float64(2), int64(1), object(14)
memory usage: 12.7+ MB

# 2. 답변 데이터셋만 사용

데이터량이 많으므로 답변 데이터 랜덤으로 1만개 뽑아서 진행

In [9]:
sample_b = sample_a.sample(n=10000, random_state=42)
sample_b.reset_index(drop=True, inplace=True)

In [10]:
sample_b.head()

,파일이름,질병_카테고리,질병,부서,의도,답변_intro,답변_body,답변_conclusion,단어수,폴더명,유형,답변
0,HC-A-02273426,근골격질환,손목 수근관 증후군,신경외과,약물,손목 수근관 증후군은 통증 완화와 기능 개선을 위해 다양한 치료 방법을 사용할 수 ...,"약물 치료는 통증 완화를 위해 일반적으로 사용되며, 주로 비스테로이드성 항염증 약물...",수술은 통증이 심한 경우 고려될 수 있습니다. 만약 수술이 필요하다면 의사와 상담하...,65,손목 수근관 증후군 - 약물,약물,손목 수근관 증후군은 통증 완화와 기능 개선을 위해 다양한 치료 방법을 사용할 수 ...
1,HC-A-02279763,근골격질환,강직성 척추염,내과,재활,"강직성 척추염은 척추와 관련된 염증성 질환으로, 조기 치료와 관리가 필요합니다. 치...",치료적 운동으로는 유연성과 강도를 향상시키는 스트레칭이 효과적입니다. 수중 물리치료...,개별 환자의 상태와 증상에 따라 개인화된 운동 계획을 세우는 것이 중요합니다. 운동...,77,강직성 척추염 - 재활,재활,"강직성 척추염은 척추와 관련된 염증성 질환으로, 조기 치료와 관리가 필요합니다. 치..."
2,HC-A-02283340,근골격질환,골수염,내과,치료,"골수염은 골 부위에 발생하는 감염성 질환으로, 주로 진균에 의해 발생합니다.",진균성 골수염은 항생제 치료와 수술로 치료될 수 있습니다. 항생제는 세균의 증식을 ...,"골수염은 치료가 중요한 질환이며, 항생제 치료와 수술적인 처리를 통해 치료될 수 있...",70,골수염 - 치료,치료,"골수염은 골 부위에 발생하는 감염성 질환으로, 주로 진균에 의해 발생합니다. 진균성..."
3,HC-A-02299902,근골격질환,손목 수근관 증후군,신경외과,"식이, 생활",손목 수근관 증후군은 주로 손목의 손목 터널 안에 있는 정중 신경과 그 주변 조직들...,"첫째로, 손목과 손가락의 자세를 바르게 유지하는 것이 중요합니다. 손바닥을 위로 향...",손목 수근관 증후군은 예방하기 위한 특정한 예방 조치와 활동으로 증상을 완화할 수 ...,109,"손목 수근관 증후군 - 식이, 생활","식이, 생활",손목 수근관 증후군은 주로 손목의 손목 터널 안에 있는 정중 신경과 그 주변 조직들...
4,HC-A-06524665,근골격질환,손목 수근관 증후군,정형외과,진단,"손목 수근관 증후군을 진단하는 방법은 다양하지만, 이들은 증상의 특징과 함께 다른 ...","일반적으로 신경 타진 검사가 주로 실시되며, 이를 통해 손목 수근관 증후군을 진단하...","손목 수근관 증후군의 진단은 신경 타진 검사, 수근 굴곡 검사, 전기적 검사 등을 ...",87,손목 수근관 증후군 - 진단,진단,"손목 수근관 증후군을 진단하는 방법은 다양하지만, 이들은 증상의 특징과 함께 다른 ..."

In [11]:
col = ['질병_카테고리','질병','부서','의도','답변']
sample_b = sample_b[col]
sample_b.head()

,질병_카테고리,질병,부서,의도,답변
0,근골격질환,손목 수근관 증후군,신경외과,약물,손목 수근관 증후군은 통증 완화와 기능 개선을 위해 다양한 치료 방법을 사용할 수 ...
1,근골격질환,강직성 척추염,내과,재활,"강직성 척추염은 척추와 관련된 염증성 질환으로, 조기 치료와 관리가 필요합니다. 치..."
2,근골격질환,골수염,내과,치료,"골수염은 골 부위에 발생하는 감염성 질환으로, 주로 진균에 의해 발생합니다. 진균성..."
3,근골격질환,손목 수근관 증후군,신경외과,"식이, 생활",손목 수근관 증후군은 주로 손목의 손목 터널 안에 있는 정중 신경과 그 주변 조직들...
4,근골격질환,손목 수근관 증후군,정형외과,진단,"손목 수근관 증후군을 진단하는 방법은 다양하지만, 이들은 증상의 특징과 함께 다른 ..."

# 3. 모델링

In [12]:
!pip install -q sentence-transformers chromadb

In [13]:
# 1. 필요 라이브러리
import pandas as pd
from sentence_transformers import SentenceTransformer
import chromadb
from chromadb.utils import embedding_functions
from tqdm import tqdm
import numpy as np

/usr/local/lib/python3.10/dist-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange

In [14]:
# 2. 임베딩 모델 로드
model = SentenceTransformer("jhgan/ko-sroberta-multitask")

# 3. Chroma 클라이언트 설정
chroma_client = chromadb.PersistentClient(path="./chroma_db")

# 4. 컬렉션 생성
embedding_function = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="jhgan/ko-sroberta-multitask")
collection = chroma_client.get_or_create_collection(name="korean_qa_collection", embedding_function=embedding_function)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [15]:
# 5. 데이터 임베딩 및 Chroma DB에 추가
batch_size = 1000  # 한 번에 처리할 데이터 수

all_documents = sample_b['답변'].tolist()
all_embeddings = model.encode(all_documents, show_progress_bar=True, batch_size=32)

for i in tqdm(range(0, len(sample_b), batch_size)):
    batch = sample_b.iloc[i:i+batch_size]

    ids = batch.index.astype(str).tolist()
    documents = batch['답변'].tolist()
    embeddings = all_embeddings[i:i+batch_size].tolist()

    metadata = batch[['질병_카테고리', '질병', '부서', '의도']].to_dict('records')

    collection.add(
        ids=ids,
        documents=documents,
        embeddings=embeddings,
        metadatas=metadata
    )

# 6. 질의 함수 정의
def query_similar_answers(query, n=5):
    results = collection.query(
        query_texts=[query],
        n_results=n
    )
    return results

Batches:   0%|          | 0/313 [00:00<?, ?it/s]

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4002
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4003
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4004
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4005
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4006
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4007
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4008
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4009
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4010
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4011
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4012
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4013
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4014
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4015
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4016
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4017
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4018
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4019
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4020
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4021
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4022
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4023
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4024
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4025
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4026
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4027
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4028
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4029
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4030
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4031
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4032
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4033
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4034
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4035
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4036
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4037
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4038
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4039
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4040
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4041
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4042
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4043
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4044
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4045
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4046
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4047
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4048
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4049
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4050
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4051
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4052
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4053
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4054
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4055
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4056
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4057
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4058
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4059
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4060
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4061
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4062
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4063
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4064
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4065
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4066
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4067
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4068
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4069
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4070
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4071
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4072
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4073
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4074
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4075
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4076
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4077
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4078
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4079
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4080
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4081
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4082
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4083
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4084
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4085
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4086
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4087
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4088
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4089
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4090
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4091
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4092
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4093
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4094
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4095
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4096
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4097
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4098
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4099
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4100
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4101
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4102
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4103
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4104
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4105
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4106
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4107
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4108
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4109
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4110
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4111
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4112
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4113
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4114
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4115
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4116
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4117
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4118
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4119
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4120
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4121
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4122
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4123
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4124
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4125
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4126
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4127
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4128
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4129
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4130
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4131
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4132
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4133
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4134
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4135
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4136
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4137
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4138
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4139
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4140
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4141
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4142
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4143
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4144
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4145
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4146
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4147
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4148
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4149
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4150
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4151
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4152
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4153
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4154
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4155
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4156
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4157
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4158
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4159
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4160
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4161
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4162
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4163
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4164
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4165
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4166
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4167
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4168
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4169
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4170
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4171
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4172
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4173
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4174
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4175
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4176
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4177
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4178
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4179
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4180
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4181
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4182
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4183
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4184
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4185
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4186
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4187
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4188
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4189
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4190
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4191
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4192
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4193
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4194
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4195
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4196
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4197
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4198
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4199
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4200
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4201
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4202
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4203
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4204
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4205
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4206
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4207
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4208
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4209
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4210
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4211
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4212
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4213
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4214
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4215
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4216
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4217
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4218
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4219
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4220
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4221
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4222
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4223
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4224
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4225
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4226
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4227
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4228
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4229
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4230
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4231
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4232
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4233
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4234
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4235
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4236
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4237
WARNING:chromadb.segment.impl.metadata.sqlite:Insert of existing embedding ID: 4238

In [16]:
user_query = "손목 수근관 증후군은 통증 완화와 기능 개선을 위해 어떤 방법을 사용해야할까요?"
similar_answers = query_similar_answers(user_query)
print(similar_answers)

{'ids': [['8575', 'HC-A-02290602', '406', 'HC-A-02273253', '5166']], 'distances': [[40.37790298461914, 41.203346252441406, 41.203346252441406, 41.45351791381836, 41.45351791381836]], 'metadatas': [[{'부서': '신경외과', '의도': '검진', '질병': '손목 수근관 증후군', '질병_카테고리': '근골격질환'}, {'부서': '신경외과', '의도': '식이, 생활', '질병': '손목 수근관 증후군', '질병_카테고리': '근골격질환'}, {'부서': '신경외과', '의도': '식이, 생활', '질병': '손목 수근관 증후군', '질병_카테고리': '근골격질환'}, {'부서': '신경외과', '의도': '검진', '질병': '손목 수근관 증후군', '질병_카테고리': '근골격질환'}, {'부서': '신경외과', '의도': '검진', '질병': '손목 수근관 증후군', '질병_카테고리': '근골격질환'}]], 'embeddings': None, 'documents': [['손목 수근관 증후군은 손목터널증후군으로도 알려져 있습니다. 이 질환은 주로 손목과 손가락에 나타나는 증상을 유발하며, 증상의 정도와 위치에 따라 치료 방법이 결정됩니다. 치료에는 약물 요법과 물리치료가 사용됩니다. 약물 요법은 소염 진통제를 투여하여 통증을 완화하고 염증을 줄일 수 있습니다. 물리치료는 근력 강화 운동, 보조 장치 사용, 물리 치료, 마사지 등을 통해 통증을 완화하고 기능을 개선하는 데 도움이 됩니다. 손목 수근관 증후군은 적절한 치료로 증상을 완화하고 기능을 회복시킬 수 있습니다. 하지만 재발할 수 있는 위험이 있으므로, 예방에 주의해야 합니다.', '손목 수근관 증후군은 손의 힘줄과 신경을 압박하여 다양한 증상을 일으키는 질환입니다. 수근관 증후군을 완화하기 위해서는 아래의 몇 가지 조치를 취할 수 있습니다. 1. 손목 운동: 손목 운동은 손목의 통증을 완화하는 데 도움이 될 수 있습니다. 손목의 굽힘과 펼침 동작을 제한하고 손목에 가해지는 압력을 줄일 수 있습니다. 손목 운동은 손목의 움직임을 개선하고 증상을 완화하는 데 도움이 됩니다. 만약 손목에 통증이 있다면, 전문가와 상담하여 적절한 운동법과 치료 방법을 찾는 것이 좋습니다.', '손목 수근관 증후군은 손의 힘줄과 신경을 압박하여 다양한 증상을 일으키는 질환입니다. 수근관 증후군을 완화하기 위해서는 아래의 몇 가지 조치를 취할 수 있습니다. 1. 손목 운동: 손목 운동은 손목의 통증을 완화하는 데 도움이 될 수 있습니다. 손목의 굽힘과 펼침 동작을 제한하고 손목에 가해지는 압력을 줄일 수 있습니다. 손목 운동은 손목의 움직임을 개선하고 증상을 완화하는 데 도움이 됩니다. 만약 손목에 통증이 있다면, 전문가와 상담하여 적절한 운동법과 치료 방법을 찾는 것이 좋습니다.', '손목 수근관 증후군은 손목을 감싸는 인대 조직의 손상으로 인해 발생하는 질환입니다. 수근관 증후군은 손목 통증과 관련된 증상으로 나타나며, 대부분은 질병의 원인을 찾는 것보다 증상을 완화하고 통증을 관리하는 것이 주된 치료입니다. 손목 수근관 증후군의 치료 방법은 다양한 접근법이 있습니다. 가장 일반적인 치료 방법은 휴식과 약물 치료입니다. 휴식은 손목 근육을 강화시키고, 통증과 염증을 감소시키는 데 도움을 줄 수 있습니다. 약물 치료는 통증 완화와 염증 감소에 도움을 줄 수 있습니다. 비스테로이드성 소염제와 스테로이드 주사는 주로 사용되는 치료법입니다. 손목 수근관 증후군의 치료 목표는 통증과 증상을 완화하고 염증을 완화시키는 것입니다. 치료 방법은 환자의 개별적인 상황과 증상에 따라 결정되어야 합니다. 의사의 지시에 따라 적합한 치료 방법을 선택하고, 지속적인 관리와 지속적인 평가가 필요합니다.', '손목 수근관 증후군은 손목을 감싸는 인대 조직의 손상으로 인해 발생하는 질환입니다. 수근관 증후군은 손목 통증과 관련된 증상으로 나타나며, 대부분은 질병의 원인을 찾는 것보다 증상을 완화하고 통증을 관리하는 것이 주된 치료입니다. 손목 수근관 증후군의 치료 방법은 다양한 접근법이 있습니다. 가장 일반적인 치료 방법은 휴식과 약물 치료입니다. 휴식은 손목 근육을 강화시키고, 통증과 염증을 감소시키는 데 도움을 줄 수 있습니다. 약물 치료는 통증 완화와 염증 감소에 도움을 줄 수 있습니다. 비스테로이드성 소염제와 스테로이드 주사는 주로 사용되는 치료법입니다. 손목 수근관 증후군의 치료 목표는 통증과 증상을 완화하고 염증을 완화시키는 것입니다. 치료 방법은 환자의 개별적인 상황과 증상에 따라 결정되어야 합니다. 의사의 지시에 따라 적합한 치료 방법을 선택하고, 지속적인 관리와 지속적인 평가가 필요합니다.']], 'uris': None, 'data': None, 'included': ['metadatas', 'documents', 'distances']}

In [17]:
similar_answers

{'ids': [['8575', 'HC-A-02290602', '406', 'HC-A-02273253', '5166']],
 'distances': [[40.37790298461914,
   41.203346252441406,
   41.203346252441406,
   41.45351791381836,
   41.45351791381836]],
 'metadatas': [[{'부서': '신경외과',
    '의도': '검진',
    '질병': '손목 수근관 증후군',
    '질병_카테고리': '근골격질환'},
   {'부서': '신경외과', '의도': '식이, 생활', '질병': '손목 수근관 증후군', '질병_카테고리': '근골격질환'},
   {'부서': '신경외과', '의도': '식이, 생활', '질병': '손목 수근관 증후군', '질병_카테고리': '근골격질환'},
   {'부서': '신경외과', '의도': '검진', '질병': '손목 수근관 증후군', '질병_카테고리': '근골격질환'},
   {'부서': '신경외과', '의도': '검진', '질병': '손목 수근관 증후군', '질병_카테고리': '근골격질환'}]],
 'embeddings': None,
 'documents': [['손목 수근관 증후군은 손목터널증후군으로도 알려져 있습니다. 이 질환은 주로 손목과 손가락에 나타나는 증상을 유발하며, 증상의 정도와 위치에 따라 치료 방법이 결정됩니다. 치료에는 약물 요법과 물리치료가 사용됩니다. 약물 요법은 소염 진통제를 투여하여 통증을 완화하고 염증을 줄일 수 있습니다. 물리치료는 근력 강화 운동, 보조 장치 사용, 물리 치료, 마사지 등을 통해 통증을 완화하고 기능을 개선하는 데 도움이 됩니다. 손목 수근관 증후군은 적절한 치료로 증상을 완화하고 기능을 회복시킬 수 있습니다. 하지만 재발할 수 있는 위험이 있으므로, 예방에 주의해야 합니다.',
   '손목 수근관 증후군은 손의 힘줄과 신경을 압박하여 다양한 증상을 일으키는 질환입니다. 수근관 증후군을 완화하기 위해서는 아래의 몇 가지 조치를 취할 수 있습니다. 1. 손목 운동: 손목 운동은 손목의 통증을 완화하는 데 도움이 될 수 있습니다. 손목의 굽힘과 펼침 동작을 제한하고 손목에 가해지는 압력을 줄일 수 있습니다. 손목 운동은 손목의 움직임을 개선하고 증상을 완화하는 데 도움이 됩니다. 만약 손목에 통증이 있다면, 전문가와 상담하여 적절한 운동법과 치료 방법을 찾는 것이 좋습니다.',
   '손목 수근관 증후군은 손의 힘줄과 신경을 압박하여 다양한 증상을 일으키는 질환입니다. 수근관 증후군을 완화하기 위해서는 아래의 몇 가지 조치를 취할 수 있습니다. 1. 손목 운동: 손목 운동은 손목의 통증을 완화하는 데 도움이 될 수 있습니다. 손목의 굽힘과 펼침 동작을 제한하고 손목에 가해지는 압력을 줄일 수 있습니다. 손목 운동은 손목의 움직임을 개선하고 증상을 완화하는 데 도움이 됩니다. 만약 손목에 통증이 있다면, 전문가와 상담하여 적절한 운동법과 치료 방법을 찾는 것이 좋습니다.',
   '손목 수근관 증후군은 손목을 감싸는 인대 조직의 손상으로 인해 발생하는 질환입니다. 수근관 증후군은 손목 통증과 관련된 증상으로 나타나며, 대부분은 질병의 원인을 찾는 것보다 증상을 완화하고 통증을 관리하는 것이 주된 치료입니다. 손목 수근관 증후군의 치료 방법은 다양한 접근법이 있습니다. 가장 일반적인 치료 방법은 휴식과 약물 치료입니다. 휴식은 손목 근육을 강화시키고, 통증과 염증을 감소시키는 데 도움을 줄 수 있습니다. 약물 치료는 통증 완화와 염증 감소에 도움을 줄 수 있습니다. 비스테로이드성 소염제와 스테로이드 주사는 주로 사용되는 치료법입니다. 손목 수근관 증후군의 치료 목표는 통증과 증상을 완화하고 염증을 완화시키는 것입니다. 치료 방법은 환자의 개별적인 상황과 증상에 따라 결정되어야 합니다. 의사의 지시에 따라 적합한 치료 방법을 선택하고, 지속적인 관리와 지속적인 평가가 필요합니다.',
   '손목 수근관 증후군은 손목을 감싸는 인대 조직의 손상으로 인해 발생하는 질환입니다. 수근관 증후군은 손목 통증과 관련된 증상으로 나타나며, 대부분은 질병의 원인을 찾는 것보다 증상을 완화하고 통증을 관리하는 것이 주된 치료입니다. 손목 수근관 증후군의 치료 방법은 다양한 접근법이 있습니다. 가장 일반적인 치료 방법은 휴식과 약물 치료입니다. 휴식은 손목 근육을 강화시키고, 통증과 염증을 감소시키는 데 도움을 줄 수 있습니다. 약물 치료는 통증 완화와 염증 감소에 도움을 줄 수 있습니다. 비스테로이드성 소염제와 스테로이드 주사는 주로 사용되는 치료법입니다. 손목 수근관 증후군의 치료 목표는 통증과 증상을 완화하고 염증을 완화시키는 것입니다. 치료 방법은 환자의 개별적인 상황과 증상에 따라 결정되어야 합니다. 의사의 지시에 따라 적합한 치료 방법을 선택하고, 지속적인 관리와 지속적인 평가가 필요합니다.']],
 'uris': None,
 'data': None,
 'included': ['metadatas', 'documents', 'distances']}